### ISSUE TITLE
Audio stops working for no real reason. 

### ISSUE THREAD

**Issue by EdPhon3z** [adlerluiz/ytmdesktop#807] opened 2021-09-02 14:38 UTC
- [X ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X ] I verified that there is no open issue for the same subject.

 **Describe the bug**
Audio stops working for no real reason. 

 **To Reproduce**
 1. I clicked the back track button

 **Expected behavior**
Sound should happen.. 

** Ways to overcome **
Restart player.

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.19042***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by koskrit** [comment] 2021-09-02 14:55
Hi EdPhon3z,

I'd like to give it a try, if that's ok with you.

**Comment by Alipoodle** [comment] 2021-09-02 15:16
On it's own there's not enough information provided here to know what is going.
Are you able to provide a bit more information to what actually happens after this issues happens?

Does the track continue playing with no sound?
Does the track pause and fail to play?

Currently I'm unable to reproduce this with a YT Video, YTM Song, Uploaded Song, even with trying to go to some of the extremes and playing an hour long video/uploaded song.

**Comment by Alipoodle** [comment] 2021-10-14 21:26
No information provided after 12 days.
Closing issue.

**Closed as completed by Alipoodle** 2021-10-14 21:26 UTC
