### ISSUE TITLE
Rich presence has stopped functioning properly.

### ISSUE THREAD

**Issue by GeneStarwind09** [adlerluiz/ytmdesktop#1372] opened 2024-06-08 18:32 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When I try to use Discord with YTMDesktop now, the rich presence gets stuck on the first song that's loaded and is super janky. It'll do a countdown but then be stuck at 0:00.

### Expected Behavior

YTMDesktop should support rich presence seamlessly, updating the name on track change and tracking the progress without issue.

### Steps To Reproduce

1. Open YTMDesktop
2. Open Discord
3. Enable Discord integration
4. Play some music
5. Check the rich presence on Discord

### YTMDesktop

2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

It was working fine weeks ago, maybe an update to YouTube broke it?

**Comment by Alipoodle** [comment] 2024-06-08 18:37
Looking at my own and multiple other users' Rich Presences this does not appear to be the case?

Although this could be a A/B thing so I can't leave that on the table.

**Comment by GeneStarwind09** [comment] 2024-06-08 18:41
I've been getting this behaviour while trying to play community playlists, maybe try those.

Edit: Wait, it's not just rich presence. I turned on the progress bar on taskbar. First track of playlist is 0:30. I go forward to a track that's about two minutes. Progress bar finishes in thirty seconds, i.e. track number one. Maybe notifications aren't working too. Wish I could tell you more, got no idea what's causing this.

**Comment by Alipoodle** [comment] 2024-06-08 19:03
Could you share the link to the playlist?

**Comment by GeneStarwind09** [comment] 2024-06-08 19:21
Sure, this is the last one I tried: https://www.youtube.com/watch?v=6suINC-tAZU&list=PL3-XFrU0Gj6lCJmooIqRJX-kYwhP3fOce

**Comment by Alipoodle** [comment] 2024-06-08 19:33
😕 was not able to reproduce the issue running the song/playlist via the URI schema to swap to that.
`ytmd://play/6suINC-tAZU/PL3-XFrU0Gj6lCJmooIqRJX-kYwhP3fOce`

Otherwise I am on a premium account so it did basically convert this to the YouTube Music version of this as songs and not Videos. https://music.youtube.com/playlist?list=OLAK5uy_lBpkC8yiin5wNFVhhyHgv_nPhu3kGFeHk

Can I please get you to take a photo of the version you are on from the Settings -> About?

**Comment by GeneStarwind09** [comment] 2024-06-08 20:01
Yep, I'm on YouTube Premium too. Screenshots, yeah, actually I've taken a couple.

Version number:

![Screenshot 2024-06-08 205112](https://github.com/ytmdesktop/ytmdesktop/assets/11772200/4fe54879-d5fa-4339-a38b-74b6ef1c6c38)

Now this screenshot demonstrates the bugs I'm experiencing affecting the main interface too. As you'll see from the track list (symbol to pause) the currently playing song is Never Fade Away from Cyberpunk 2077. However, you'll see that it's displaying the album cover and a track title from the Welcome to the NHK soundtrack below. That'll probably be a song I played shortly before switching to the Cyberpunk playlist.

![Screenshot 2024-06-08 205033](https://github.com/ytmdesktop/ytmdesktop/assets/11772200/6aa95f55-23c0-418a-9735-5d5304f0e22e)

I take it that YTMDesktop is completely unaffected by extensions I might have installed to Google Chrome? Just wanted to rule that out as I do have some extensions that change YouTube in ways.

**Comment by NovusTheory** [comment] 2024-06-08 23:17
> However, you'll see that it's displaying the album cover and a track title from the Welcome to the NHK soundtrack below. That'll probably be a song I played shortly before switching to the Cyberpunk playlist.

This is a YTM bug that I even sometimes encounter. No idea what causes it but it's usually fixed by just changing the song again.

**Comment by dipras** [comment] 2024-06-19 04:35
Got the same issue

**Comment by Akiisqt** [comment] 2024-07-23 01:45
I no longer have the issue in my fork, Ill see to uploading the fork to github soon. . .

**Comment by Alipoodle** [comment] 2024-07-24 12:10
@dipras  / @GeneStarwind09  any more updates on this?

**Comment by GeneStarwind09** [comment] 2024-07-24 16:27
@Alipoodle I haven't experienced this issue in quite some time, probably the last month or so. Take that with a pinch of salt though as I only play YouTube Music on my computer once or twice a week. Upon trying it right now the rich presence feature seems to be working. I'll give another update if that changes.

**Comment by dipras** [comment] 2024-08-02 04:23
> @dipras / @GeneStarwind09 any more updates on this?

@Alipoodle  I have no problem anymore with it. Thank for the update

**Comment by Alipoodle** [comment] 2024-08-02 07:13
Seems to have resolved itself

**Closed as completed by Alipoodle** 2024-08-02 07:13 UTC
