### ISSUE TITLE
sugerencia?

### ISSUE THREAD

**Issue by Maguz0** [adlerluiz/ytmdesktop#1480] opened 2024-12-13 23:38 UTC
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

pueden hacer que no tenga anuncios 👍🏻 

### Solution

menos anuncios estaria bien

**Comment by Alipoodle** [comment] 2024-12-14 00:00
Duplicate of #114

**Closed as completed by Alipoodle** 2024-12-14 00:00 UTC
