### ISSUE TITLE
Search Function Not Showing Results; Only Blank/Black Screen

### ISSUE THREAD

**Issue by Hank3** [adlerluiz/ytmdesktop#1440] opened 2024-09-16 19:10 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When using the search function, no results are shown other than a black/blank screen.

### Expected Behavior

Expect results to populate on in the app.

### Steps To Reproduce

Go to YTM Desktop App; type in search bar; will see no results.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment] 2024-09-16 20:07
Duplicate of #1435

**Closed as completed by Alipoodle** 2024-09-16 20:07 UTC
