### ISSUE TITLE
Ad block?

### ISSUE THREAD

**Issue by 48kMcFae** [adlerluiz/ytmdesktop#1410] opened 2024-08-06 14:45 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

ad block?

### Solution

kino

### Alternatives

pls

**Comment by Alipoodle** [comment] 2024-08-06 16:56
Duplicate of #114

**Closed as completed by Alipoodle** 2024-08-06 16:56 UTC
