### ISSUE TITLE
install own addons or equalizer only. 

### ISSUE THREAD

**Issue by Obstidian** [adlerluiz/ytmdesktop#1368] opened 2024-06-01 10:33 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

it would be good to add some kind of equalizer. I hardly even listen to music without an equalizer anymore, it adds depth. 

### Solution

example:
![image](https://github.com/ytmdesktop/ytmdesktop/assets/128893964/7b8e42c4-c0a6-4862-b16e-cfa781acb6af)

link to most customizable equalizer on google extensions (imo): https://chromewebstore.google.com/detail/ears-bass-boost-eq-any-au/nfdfiepdkbnoanddpianalelglmfooik?pli=1

### Alternatives

install own addons or voicemeeter, but i don´t want to install something on whole system just for one app.

**Comment by Alipoodle** [comment] 2024-06-01 11:17
Duplicate of #592

**Closed as completed by Alipoodle** 2024-06-01 11:17 UTC

**Comment by Alipoodle** [comment] 2024-06-01 11:19
We have looked into doing an EQ but there's a few things with how to process this~
