### ISSUE TITLE
An option in the settings to prefer Song over Video

### ISSUE THREAD

**Issue by TerryS94** [adlerluiz/ytmdesktop#1477] opened 2024-12-08 22:48 UTC
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

An option in the settings to toggle to prefer Song over Video (if both song and video is present) so we don't have to manually select "song" every time would be cool.

### Solution

An option in the settings to toggle to prefer Song over Video (if both song and video is present) so we don't have to manually select "song" every time would be cool.

### Anything else?

![Image](https://github.com/user-attachments/assets/edf9bbbe-ec40-4450-8768-7184e6bb1f39)

**Comment by NovusTheory** [comment] 2024-12-08 23:45
Duplicate of #1234 

Though that issue highlights video mode being preferred it does mention the ability to swap to song or video as the preferred mode and is already a tracker for the branch that implemented a system to resolve this though it hasn't been put in a release yet.

In more recent YTM updates your mode should be remembered (whereas before it wasn't) for your current queue, unless a song is in the queue without a video then it overrides your selected mode to song permanently which seems like it would resolve your specific issue anyways as song mode is *always* available on YTM for videos (thumbnail only fallback).

**Closed as completed by NovusTheory** 2024-12-08 23:45 UTC
